<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>eu.wohlben.qits</groupId>
        <artifactId>qits-foo-parent</artifactId>
        <version>2026.1001.1</version>
    </parent>
    <artifactId>qits-foo-bom</artifactId>
    <packaging>pom</packaging>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>eu.wohlben.qits</groupId>
                <artifactId>qits-foo-api</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
