package eu.wohlben.qits.cli.access.database;

import eu.wohlben.qits.cli.access.TestCli;
import eu.wohlben.qits.cli.access.daemon.Sleeper;
import eu.wohlben.qits.cli.access.platform.CliContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@code qits database diagram} over the fixture project: the files it writes are the golden files
 * under {@code src/test/resources/.../database/golden/} byte for byte, a second run writes the same
 * bytes, and it deletes only the generated files it did not write.
 * <p>
 * A change to the format or the mapping changes the golden files on purpose: write them again with
 * {@code ./mvnw test -Dtest=DiagramCommandTest -Dgolden.update=true} and review the diff.
 */
class DiagramCommandTest {

    private static final Path GOLDEN = Path.of("src/test/resources/eu/wohlben/qits/cli/access/database/golden");
    private static final String HEADER = "<!-- Generated by `qits database diagram` (jpa). Do not edit: the "
            + "entity-diagram automation rewrites this file on every release request fold. -->\n";

    @TempDir
    Path dir;

    private Path root;

    record Result(int exit, String out, String err) {
    }

    @BeforeEach
    void project() throws IOException {
        root = FixtureProject.create(dir.resolve("fixture"));
    }

    @Test
    void theFilesAreTheGoldenFiles() throws IOException {
        Result result = diagram("--root", root.toString());

        assertThat(result.exit()).as(result.err()).isZero();
        Map<String, String> written = files(root.resolve("docs/database"));
        if (Boolean.getBoolean("golden.update")) {
            FixtureProject.delete(GOLDEN);
            for (Map.Entry<String, String> file : written.entrySet()) {
                FixtureProject.write(GOLDEN.resolve(file.getKey()), file.getValue());
            }
        }
        assertThat(written).isEqualTo(files(GOLDEN));
        assertThat(result.out()).isEqualTo("""
                written docs/database/default.md
                written docs/database/eu.wohlben.qits.cli.access.database.fixtures.stray.md
                written docs/database/library.md
                written docs/database/model.md
                written docs/database/unsupported.md
                """);
    }

    @Test
    void aSecondRunWritesTheSameBytesAndSaysUnchanged() throws IOException {
        diagram("--root", root.toString());
        Map<String, String> first = files(root.resolve("docs/database"));

        Result second = diagram("--root", root.toString());

        assertThat(second.exit()).isZero();
        assertThat(files(root.resolve("docs/database"))).isEqualTo(first);
        assertThat(second.out().lines().toList()).hasSize(5).allMatch(line -> line.startsWith("unchanged "));
        Result check = diagram("--root", root.toString(), "--check");
        assertThat(check.exit()).isZero();
    }

    @Test
    void theWarningsNameTheProfiledKeyAndTheExpression() {
        Result result = diagram("--root", root.toString());

        assertThat(result.err()).contains("warning: ignored %dev.quarkus.hibernate-orm.devonly.packages in "
                + "app/target/classes/application.properties");
        assertThat(result.err()).contains("warning: ignored quarkus.hibernate-orm.expr.packages in "
                + "app/target/classes/application.properties: its value is an expression (${FIXTURE_PACKAGES})");
    }

    @Test
    void aStaleGeneratedFileIsDeletedAndAHandWrittenOneIsKept() throws IOException {
        Path out = root.resolve("docs/database");
        FixtureProject.write(out.resolve("retired.md"), HEADER + "# Persistence unit `retired`\n");
        FixtureProject.write(out.resolve("README.md"), "# What these files are\n");
        FixtureProject.write(out.resolve("notes.txt"), HEADER);

        Result result = diagram("--root", root.toString());

        assertThat(result.out()).contains("deleted docs/database/retired.md\n");
        assertThat(out.resolve("retired.md")).doesNotExist();
        assertThat(out.resolve("README.md")).hasContent("# What these files are");
        assertThat(out.resolve("notes.txt")).exists();
    }

    @Test
    void checkWritesNothingAndExitsOneWhenAFileWouldChange() throws IOException {
        Path out = root.resolve("docs/database");
        FixtureProject.write(out.resolve("retired.md"), HEADER);

        Result result = diagram("--root", root.toString(), "--check");

        assertThat(result.exit()).isEqualTo(1);
        assertThat(result.out()).contains("would write docs/database/model.md\n")
                .contains("would delete docs/database/retired.md\n");
        assertThat(files(out)).containsOnlyKeys("retired.md");
    }

    @Test
    void anotherOutputDirectoryIsWrittenInstead() throws IOException {
        Path elsewhere = dir.resolve("elsewhere");

        Result result = diagram("--root", root.toString(), "--out", elsewhere.toString());

        assertThat(result.exit()).isZero();
        assertThat(files(elsewhere)).containsKeys("model.md", "default.md");
        assertThat(root.resolve("docs")).doesNotExist();
    }

    @Test
    void nothingCompiledIsUsageAndSaysCompileFirst() throws IOException {
        Path bare = dir.resolve("bare");
        FixtureProject.write(bare.resolve("pom.xml"), "<project><modelVersion>4.0.0</modelVersion>"
                + "<artifactId>bare</artifactId></project>\n");

        Result result = diagram("--root", bare.toString());

        assertThat(result.exit()).isEqualTo(2);
        assertThat(result.err()).isEqualTo("compile first: no target/classes under " + bare.toAbsolutePath() + "\n");
    }

    @Test
    void noEntitiesSaysSoExitsZeroAndStillDeletesTheOldFiles() throws IOException {
        Path empty = dir.resolve("empty");
        FixtureProject.write(empty.resolve("pom.xml"), "<project><modelVersion>4.0.0</modelVersion>"
                + "<artifactId>empty</artifactId></project>\n");
        Files.createDirectories(empty.resolve("target/classes"));
        FixtureProject.write(empty.resolve("docs/database/ci.md"), HEADER);

        Result result = diagram("--root", empty.toString());

        assertThat(result.exit()).isZero();
        assertThat(result.out()).isEqualTo("deleted docs/database/ci.md\nno JPA entities found\n");
    }

    @Test
    void aRootThatIsNotADirectoryIsUsage() {
        Result result = diagram("--root", dir.resolve("missing").toString());

        assertThat(result.exit()).isEqualTo(2);
        assertThat(result.err()).contains("is not a directory");
    }

    private static Map<String, String> files(Path dir) throws IOException {
        Map<String, String> files = new TreeMap<>();
        if (!Files.isDirectory(dir)) {
            return files;
        }
        try (Stream<Path> list = Files.list(dir)) {
            for (Path file : list.toList()) {
                files.put(file.getFileName().toString(), Files.readString(file, StandardCharsets.UTF_8));
            }
        }
        return files;
    }

    private Result diagram(String... args) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        ByteArrayOutputStream err = new ByteArrayOutputStream();
        CliContext context = new CliContext(Map.of(), InputStream.nullInputStream(),
                new PrintStream(out, true, StandardCharsets.UTF_8), new PrintStream(err, true, StandardCharsets.UTF_8),
                Clock.systemUTC(), Sleeper.real(), name -> null, stop -> { });
        List<String> all = new ArrayList<>(List.of("database", "diagram"));
        all.addAll(List.of(args));
        int exit = TestCli.execute(context, all.toArray(String[]::new));
        return new Result(exit, out.toString(StandardCharsets.UTF_8), err.toString(StandardCharsets.UTF_8));
    }
}
