package eu.wohlben.qits.cli.access.database;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The file format of epic qits-760, Design §3, and its way back: the entity-changes report kind
 * parses two of these files and diffs the units, so {@code parse(render(unit))} must be the unit.
 */
class MermaidEntityDiagramFormatTest {

    private final MermaidEntityDiagramFormat format = new MermaidEntityDiagramFormat("jpa");

    private static final UnitModel CI = new UnitModel("ci", "ci.md", "Persistence unit `ci`",
            List.of("Datasource `ci`", "package `eu.wohlben.qits.ci.entity`", "2 entities"),
            List.of(
                    new TableModel("ci_step", "eu.wohlben.qits.ci.entity.CiStep", "ci", List.of(
                            new ColumnModel("id", "string", true, false, false, false, null),
                            new ColumnModel("output", "text", false, false, false, true, null),
                            new ColumnModel("run_id", "string", false, true, false, false, null))),
                    new TableModel("ci_report", "eu.wohlben.qits.ci.entity.CiReport", "ci", List.of(
                            new ColumnModel("id", "uuid", true, false, false, false, null, List.of("generated")),
                            new ColumnModel("kind", "string", false, false, true, false, 64),
                            new ColumnModel("payload", "text", false, false, false, false, null, List.of("lob"))))),
            List.of(new RelationModel("ci_step", "ci_run", "run_id", false),
                    new RelationModel("ci_report", "ci_run", "run_id", true)),
            List.of("`CiRun.steps` (`@ManyToMany`)"));

    @Test
    void rendersDesignSectionThree() {
        assertThat(format.render(CI)).isEqualTo("""
                <!-- Generated by `qits database diagram` (jpa). Do not edit: the entity-diagram automation \
                rewrites this file on every release request fold. -->
                # Persistence unit `ci`

                Datasource `ci` · package `eu.wohlben.qits.ci.entity` · 2 entities

                ```mermaid
                erDiagram
                  %% ci_report: eu.wohlben.qits.ci.entity.CiReport (ci)
                  ci_report {
                    uuid id PK "not null, generated"
                    string kind UK "not null, length 64"
                    text payload "not null, lob"
                  }
                  %% ci_step: eu.wohlben.qits.ci.entity.CiStep (ci)
                  ci_step {
                    string id PK "not null"
                    text output
                    string run_id FK "not null"
                  }
                  ci_report }o--o| ci_run : "run_id"
                  ci_step }o--|| ci_run : "run_id"
                  %% not drawn: `CiRun.steps` (`@ManyToMany`)
                ```

                - Not drawn: `CiRun.steps` (`@ManyToMany`)
                """);
    }

    @Test
    void parseReadsBackWhatRenderWrote() {
        UnitModel parsed = format.parse(format.render(CI));

        assertThat(parsed.name()).isEqualTo("ci");
        assertThat(parsed.fileName()).isEqualTo("ci.md");
        assertThat(parsed.heading()).isEqualTo(CI.heading());
        assertThat(parsed.notes()).isEqualTo(CI.notes());
        assertThat(parsed.tables()).containsExactlyElementsOf(CI.tables().stream()
                .sorted((a, b) -> a.name().compareTo(b.name())).toList());
        assertThat(parsed.relations()).containsExactlyElementsOf(MermaidEntityDiagramFormat.sortedRelations(CI.relations()));
        assertThat(parsed.notDrawn()).isEqualTo(CI.notDrawn());
        assertThat(format.render(parsed)).isEqualTo(format.render(CI));
    }

    @Test
    void everyGoldenFileRoundTrips() throws IOException {
        Path golden = Path.of("src/test/resources/eu/wohlben/qits/cli/access/database/golden");
        List<Path> files;
        try (Stream<Path> list = Files.list(golden)) {
            files = list.sorted().toList();
        }
        assertThat(files).isNotEmpty();
        for (Path file : files) {
            String text = Files.readString(file);
            UnitModel unit = format.parse(text);
            assertThat(unit.fileName()).as(file.toString()).isEqualTo(file.getFileName().toString());
            assertThat(format.render(unit)).as(file.toString()).isEqualTo(text);
            assertThat(MermaidEntityDiagramFormat.isGenerated(text)).isTrue();
        }
    }

    @Test
    void theDefaultUnitIsWrittenToDefaultMd() {
        UnitModel unit = new UnitModel("<default>", "default.md", "Persistence unit `<default>`", List.of(), List.of(),
                List.of(), List.of());

        UnitModel parsed = format.parse(format.render(unit));

        assertThat(parsed.name()).isEqualTo("<default>");
        assertThat(parsed.fileName()).isEqualTo("default.md");
        assertThat(parsed.tables()).isEmpty();
        assertThat(parsed.notes()).isEmpty();
    }

    @Test
    void parseIsLenientAboutLineEndingsAndStrayLines() {
        String text = format.render(CI).replace("\n", "\r\n").replace("erDiagram\r\n", "erDiagram\r\n\r\n  %% hello\r\n")
                + "\r\nSome words a person added.\r\n";

        UnitModel parsed = format.parse(text);

        assertThat(parsed.tables()).hasSize(2);
        assertThat(parsed.relations()).hasSize(2);
        assertThat(parsed.notDrawn()).containsExactly("`CiRun.steps` (`@ManyToMany`)");
    }

    @Test
    void parseOfSomethingElseIsAnEmptyUnitNotAnError() {
        UnitModel parsed = format.parse("just some text\nwith no diagram\n");

        assertThat(parsed.tables()).isEmpty();
        assertThat(parsed.relations()).isEmpty();
        assertThat(format.parse(null).tables()).isEmpty();
    }

    @Test
    void aTableWithoutItsCommentLineHasNoClassAndNoOrigin() {
        UnitModel parsed = format.parse("# Persistence unit `x`\n```mermaid\nerDiagram\n  t {\n    int a PK\n  }\n```\n");

        assertThat(parsed.tables()).containsExactly(new TableModel("t", null, null,
                List.of(new ColumnModel("a", "int", true, false, false, true, null))));
    }

    @Test
    void onlyAFileThatStartsWithTheHeaderIsGenerated() {
        assertThat(MermaidEntityDiagramFormat.isGenerated(format.render(CI))).isTrue();
        assertThat(MermaidEntityDiagramFormat.isGenerated("# Notes\n" + format.render(CI))).isFalse();
        assertThat(MermaidEntityDiagramFormat.isGenerated("")).isFalse();
    }

    @Test
    void theOutputHasLfEndingsAndOneTrailingNewline() {
        String text = format.render(CI);

        assertThat(text).doesNotContain("\r").endsWith("\n").doesNotEndWith("\n\n");
    }
}
