package eu.wohlben.qits.cli.access.database;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The diagram as Markdown with one fenced Mermaid {@code erDiagram} block (epic qits-760, Design §3):
 * it renders on the GitHub mirror and in qits-docs, and it is plain text for {@code git diff}.
 * <p>
 * {@link #render} writes nothing that varies between runs: no version, no timestamp, no absolute
 * path, LF line endings and one trailing newline. Tables are sorted by name, relations by (from, to,
 * column) and the "Not drawn" entries alphabetically; a table's columns are written in the order the
 * source gives them (the key first, in key order, then the rest by name).
 * <p>
 * {@link #parse} reads back what {@link #render} writes, and is lenient about anything else: CRLF,
 * extra blank lines and lines it does not know are skipped, never refused. The entity-changes report
 * kind diffs two files through it.
 */
public final class MermaidEntityDiagramFormat implements EntityDiagramFormat {

    /** How every generated file starts. The generator deletes only files that start this way. */
    public static final String HEADER_PREFIX = "<!-- Generated by `qits database diagram`";

    private static final String HEADER_SUFFIX = ". Do not edit: the entity-diagram automation rewrites this file on "
            + "every release request fold. -->";
    private static final String NOTE_SEPARATOR = " · ";
    private static final String NOT_DRAWN_COMMENT = "%% not drawn: ";
    private static final String NOT_DRAWN_ITEM = "- Not drawn: ";
    private static final String FENCE = "```";

    private static final Pattern TABLE_COMMENT = Pattern.compile("^%%\\s*([^\\s:]+):\\s*(.*?)\\s*(?:\\(([^()]*)\\))?\\s*$");
    private static final Pattern TABLE_OPEN = Pattern.compile("^([^\\s{]+)\\s*\\{\\s*$");
    private static final Pattern RELATION = Pattern.compile(
            "^(\\S+)\\s+([|}][|o](?:--|\\.\\.)[|o][|{])\\s+(\\S+)\\s*:\\s*(.*?)\\s*$");
    private static final Pattern LENGTH = Pattern.compile("^length\\s+(\\d+)$");
    private static final Pattern BACKTICKED = Pattern.compile("`([^`]+)`");

    private final String sourceId;

    /** {@code sourceId} is named in the header: {@code jpa}. */
    public MermaidEntityDiagramFormat(String sourceId) {
        this.sourceId = sourceId;
    }

    /** True when {@code text} is a file this generator wrote: its first line is the header. */
    public static boolean isGenerated(String text) {
        if (text == null) {
            return false;
        }
        String stripped = text.startsWith("﻿") ? text.substring(1) : text;
        return stripped.stripLeading().startsWith(HEADER_PREFIX);
    }

    /** The file a unit of this name is written to: the name, without angle brackets, and {@code .md}. */
    public static String fileNameOf(String unitName) {
        return unitName.replace("<", "").replace(">", "") + ".md";
    }

    @Override
    public String render(UnitModel unit) {
        StringBuilder out = new StringBuilder();
        out.append(HEADER_PREFIX).append(" (").append(sourceId).append(')').append(HEADER_SUFFIX).append('\n');
        out.append("# ").append(unit.heading()).append('\n');
        if (!unit.notes().isEmpty()) {
            out.append('\n').append(String.join(NOTE_SEPARATOR, unit.notes())).append('\n');
        }
        out.append('\n').append(FENCE).append("mermaid\n").append("erDiagram\n");
        List<TableModel> tables = new ArrayList<>(unit.tables());
        tables.sort(Comparator.comparing(TableModel::name));
        for (TableModel table : tables) {
            out.append("  %% ").append(table.name()).append(": ").append(table.javaClass())
                    .append(" (").append(table.origin()).append(")\n");
            out.append("  ").append(table.name()).append(" {\n");
            for (ColumnModel column : table.columns()) {
                out.append("    ").append(column.type()).append(' ').append(column.name());
                List<String> keys = keys(column);
                if (!keys.isEmpty()) {
                    out.append(' ').append(String.join(", ", keys));
                }
                List<String> comment = comment(column);
                if (!comment.isEmpty()) {
                    out.append(" \"").append(String.join(", ", comment)).append('"');
                }
                out.append('\n');
            }
            out.append("  }\n");
        }
        for (RelationModel relation : sortedRelations(unit.relations())) {
            out.append("  ").append(relation.from()).append(relation.optional() ? " }o--o| " : " }o--|| ")
                    .append(relation.to()).append(" : \"").append(relation.column()).append("\"\n");
        }
        List<String> notDrawn = List.copyOf(new TreeSet<>(unit.notDrawn()));
        for (String entry : notDrawn) {
            out.append("  ").append(NOT_DRAWN_COMMENT).append(entry).append('\n');
        }
        out.append(FENCE).append('\n');
        if (!notDrawn.isEmpty()) {
            out.append('\n');
            for (String entry : notDrawn) {
                out.append(NOT_DRAWN_ITEM).append(entry).append('\n');
            }
        }
        return out.toString();
    }

    /** Relations in the file's order: by from, to, then column. */
    public static List<RelationModel> sortedRelations(List<RelationModel> relations) {
        List<RelationModel> sorted = new ArrayList<>(relations);
        sorted.sort(Comparator.comparing(RelationModel::from).thenComparing(RelationModel::to)
                .thenComparing(RelationModel::column));
        return sorted;
    }

    private static List<String> keys(ColumnModel column) {
        List<String> keys = new ArrayList<>(3);
        if (column.primaryKey()) {
            keys.add("PK");
        }
        if (column.foreignKey()) {
            keys.add("FK");
        }
        if (column.unique()) {
            keys.add("UK");
        }
        return keys;
    }

    private static List<String> comment(ColumnModel column) {
        List<String> parts = new ArrayList<>();
        if (!column.nullable()) {
            parts.add("not null");
        }
        if (column.length() != null) {
            parts.add("length " + column.length());
        }
        parts.addAll(column.flags());
        return parts;
    }

    /**
     * The unit a file describes. What the file does not say is empty or null: a table with no
     * {@code %%} line before it has no class and no origin, a file with no heading has the name
     * {@code ""}.
     */
    @Override
    public UnitModel parse(String text) {
        List<String> lines = (text == null ? "" : text).replace("\r\n", "\n").replace('\r', '\n').lines().toList();
        String heading = null;
        List<String> notes = new ArrayList<>();
        List<TableModel> tables = new ArrayList<>();
        List<RelationModel> relations = new ArrayList<>();
        List<String> notDrawnItems = new ArrayList<>();
        List<String> notDrawnComments = new ArrayList<>();

        int i = 0;
        // Before the block: the heading and the summary line.
        for (; i < lines.size(); i++) {
            String line = lines.get(i).strip();
            if (line.startsWith(FENCE)) {
                break;
            }
            if (line.isEmpty() || line.startsWith("<!--")) {
                continue;
            }
            if (heading == null && line.startsWith("#")) {
                heading = line.replaceFirst("^#+\\s*", "");
            } else if (heading != null && notes.isEmpty()) {
                for (String note : line.split(Pattern.quote(NOTE_SEPARATOR.strip()))) {
                    if (!note.isBlank()) {
                        notes.add(note.strip());
                    }
                }
            }
        }
        // The block.
        boolean inBlock = false;
        String pendingClass = null;
        String pendingOrigin = null;
        String pendingName = null;
        String openTable = null;
        List<ColumnModel> columns = new ArrayList<>();
        for (; i < lines.size(); i++) {
            String line = lines.get(i).strip();
            if (line.startsWith(FENCE)) {
                if (inBlock) {
                    i++;
                    break;
                }
                inBlock = true;
                continue;
            }
            if (line.isEmpty() || line.equals("erDiagram")) {
                continue;
            }
            if (openTable != null) {
                if (line.equals("}")) {
                    boolean described = openTable.equals(pendingName);
                    tables.add(new TableModel(openTable, described ? pendingClass : null,
                            described ? pendingOrigin : null, columns));
                    openTable = null;
                    columns = new ArrayList<>();
                } else if (!line.startsWith("%%")) {
                    ColumnModel column = column(line);
                    if (column != null) {
                        columns.add(column);
                    }
                }
                continue;
            }
            if (line.startsWith(NOT_DRAWN_COMMENT.strip())) {
                notDrawnComments.add(line.substring(NOT_DRAWN_COMMENT.strip().length()).strip());
                continue;
            }
            Matcher comment = TABLE_COMMENT.matcher(line);
            if (line.startsWith("%%")) {
                if (comment.matches()) {
                    pendingName = comment.group(1);
                    pendingClass = comment.group(2).isEmpty() ? null : comment.group(2);
                    pendingOrigin = comment.group(3);
                }
                continue;
            }
            Matcher open = TABLE_OPEN.matcher(line);
            if (open.matches()) {
                openTable = open.group(1);
                continue;
            }
            Matcher relation = RELATION.matcher(line);
            if (relation.matches()) {
                String cardinality = relation.group(2);
                relations.add(new RelationModel(relation.group(1), relation.group(3), unquote(relation.group(4)),
                        cardinality.charAt(cardinality.length() - 2) == 'o'));
            }
        }
        if (openTable != null) {
            boolean described = openTable.equals(pendingName);
            tables.add(new TableModel(openTable, described ? pendingClass : null, described ? pendingOrigin : null,
                    columns));
        }
        // After the block: the "Not drawn" list.
        for (; i < lines.size(); i++) {
            String line = lines.get(i).strip();
            if (line.startsWith(NOT_DRAWN_ITEM)) {
                notDrawnItems.add(line.substring(NOT_DRAWN_ITEM.length()).strip());
            }
        }

        String name = heading == null ? "" : name(heading);
        List<String> notDrawn = notDrawnItems.isEmpty() ? notDrawnComments : notDrawnItems;
        return new UnitModel(name, name.isEmpty() ? null : fileNameOf(name), heading == null ? "" : heading, notes,
                tables, relations, List.copyOf(new TreeSet<>(notDrawn)));
    }

    private static String name(String heading) {
        Matcher backticked = BACKTICKED.matcher(heading);
        return backticked.find() ? backticked.group(1) : heading.strip();
    }

    /** One column line: {@code type name [PK][, FK][, UK] ["comment"]}; null when it is not one. */
    private static ColumnModel column(String line) {
        String body = line;
        String comment = "";
        int quote = line.indexOf('"');
        if (quote >= 0) {
            body = line.substring(0, quote);
            int end = line.lastIndexOf('"');
            comment = end > quote ? line.substring(quote + 1, end) : line.substring(quote + 1);
        }
        String[] tokens = body.strip().split("[\\s,]+");
        if (tokens.length < 2 || tokens[0].isEmpty()) {
            return null;
        }
        boolean pk = false;
        boolean fk = false;
        boolean uk = false;
        for (int t = 2; t < tokens.length; t++) {
            switch (tokens[t].toUpperCase(Locale.ROOT)) {
                case "PK" -> pk = true;
                case "FK" -> fk = true;
                case "UK" -> uk = true;
                default -> {
                    // A key Mermaid knows and this generator never writes: ignored.
                }
            }
        }
        boolean nullable = true;
        Integer length = null;
        List<String> flags = new ArrayList<>();
        for (String part : comment.split(",")) {
            String word = part.strip();
            if (word.isEmpty()) {
                continue;
            }
            Matcher lengthMatch = LENGTH.matcher(word);
            if (word.equals("not null")) {
                nullable = false;
            } else if (word.equals("null")) {
                nullable = true;
            } else if (lengthMatch.matches()) {
                length = Integer.valueOf(lengthMatch.group(1));
            } else {
                flags.add(word);
            }
        }
        return new ColumnModel(tokens[1], tokens[0], pk, fk, uk, nullable, length, flags);
    }

    private static String unquote(String label) {
        String stripped = label.strip();
        if (stripped.length() >= 2 && stripped.startsWith("\"") && stripped.endsWith("\"")) {
            return stripped.substring(1, stripped.length() - 1);
        }
        return stripped;
    }
}
